version: "3.8"

services:
  postgres-exporter-demo-patroni1:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-demo-patroni1
    networks:
      - molecule_docker_network
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@demo-patroni1:5432/postgres?sslmode=disable"
    ports:
      - "9181:9187"   # metrics для первого инстанса

  postgres-exporter-demo-patroni2:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-demo-patroni2
    networks:
      - molecule_docker_network
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@demo-patroni2:5432/postgres?sslmode=disable"
    ports:
      - "9182:9187"   # metrics для второго инстанса

  postgres-exporter-demo-patroni3:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-demo-patroni3
    networks:
      - molecule_docker_network
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@demo-patroni3:5432/postgres?sslmode=disable"
    ports:
      - "9183:9187"   # metrics для третьего инстанса

networks:
  molecule_docker_network:
    external: true


#  nodeexporter:
#    image: prom/node-exporter:v1.9.1
#    container_name: nodeexporter
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.rootfs=/rootfs'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#    restart: unless-stopped
#    network_mode: host
#    labels:
#      org.label-schema.group: "monitoring"
#
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.52.1
#    container_name: cadvisor
#    privileged: true
#    devices:
#      - /dev/kmsg:/dev/kmsg
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /cgroup:/cgroup:ro
#    restart: unless-stopped
#    network_mode: host
#    labels:
#      org.label-schema.group: "monitoring"
  

